[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "nodejs"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "echo 'Build phase completed'"

[start]
cmd = "python railway_start.py"
