[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/live-gold-price"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "python app.py"

# Auto-close learning system deployment - 2025-09-08
[variables]
AUTO_CLOSE_ENABLED = "true"
LEARNING_ENGINE_ACTIVE = "true"

[[services]]
name = "quantgold-web"
source = "."

[services.variables]
PORT = "${{ RAILWAY_PUBLIC_PORT }}"
RAILWAY_ENVIRONMENT = "production"
FLASK_ENV = "production"
PYTHONPATH = "."

[[services.healthcheck]]
path = "/"
interval = 30
timeout = 10
retries = 3
