import requests
import json

def test_local_signals():
    """Test local signal endpoints"""
    
    endpoints = [
        "http://localhost:5000/api/signals/generate",
        "http://localhost:5000/api/generate-signal"
    ]
    
    for endpoint in endpoints:
        print(f"\n🧪 Testing: {endpoint}")
        try:
            response = requests.get(endpoint, timeout=30)
            print(f"Status: {response.status_code}")
            
            if response.status_code == 200:
                data = response.json()
                print(f"Success: {data.get('success', False)}")
                if data.get('success'):
                    signal = data.get('signal', data)
                    print(f"Signal Type: {signal.get('signal_type', 'N/A')}")
                    print(f"Entry Price: ${signal.get('entry_price', 0):.2f}")
                    print(f"Generated By: {signal.get('generated_by', 'Unknown')}")
                else:
                    print(f"Error: {data.get('error', 'No error message')}")
            else:
                print(f"HTTP Error: {response.text}")
                
        except Exception as e:
            print(f"Request failed: {e}")

if __name__ == "__main__":
    test_local_signals()
