import requests
import time

try:
    print("🧪 Testing signal generation endpoint...")
    response = requests.get("http://localhost:5000/api/signals/generate", timeout=60)
    print(f"Status Code: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        print(f"Success: {data.get('success', False)}")
        if data.get('success'):
            signal = data.get('signal', data)
            print(f"✅ Signal Generated!")
            print(f"Type: {signal.get('signal_type', 'N/A')}")
            print(f"Entry: ${signal.get('entry_price', 0):.2f}")
            print(f"TP: ${signal.get('take_profit', 0):.2f}")
            print(f"SL: ${signal.get('stop_loss', 0):.2f}")
            print(f"Generated By: {signal.get('generated_by', 'Unknown')}")
        else:
            print(f"❌ Error: {data.get('error', 'Unknown')}")
    else:
        print(f"❌ HTTP Error: {response.text}")
        
except Exception as e:
    print(f"❌ Exception: {e}")
